// Code generated by goctl. DO NOT EDIT.
package types

type CommonResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

// BizError 业务错误，可被 NewCommonResponse 识别并转为 CommonResponse
type BizError struct {
	Code    int
	Message string
}

func (e *BizError) Error() string {
	return e.Message
}

// NewCommonResponse 将业务返回值或错误统一转换为 CommonResponse
func NewCommonResponse(data interface{}, err error) *CommonResponse {
	if err != nil {
		if biz, ok := err.(*BizError); ok {
			return &CommonResponse{Code: biz.Code, Message: biz.Message}
		}
		return &CommonResponse{Code: 500, Message: err.Error()}
	}
	return &CommonResponse{Code: 0, Message: "success", Data: data}
}

// RegisterRequest 公开注册请求（无需认证）
type RegisterRequest struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Phone    string `json:"phone,optional"`
	Password string `json:"password"`
}

// ValidateAPIKeyRequest 验证 API Key 请求（无需认证）
type ValidateAPIKeyRequest struct {
	APIKey string `json:"api_key"`
}

type CallContractRequest struct {
	ChainName    string            `json:"chain_name"`
	ContractName string            `json:"contract_name"`
	Method       string            `json:"method"`
	MethodType   int               `json:"method_type,optional"` // 调用类型：1-写链(Invoke) 2-读链(Query)，默认1
	Params       map[string]string `json:"params"`
	Sync         bool              `json:"sync,optional"`       // 是否同步等待上链确认，默认false（异步）
	TxTimeout    int64             `json:"tx_timeout,optional"` // 同步等待超时时间（秒），默认10
	GasLimit     int64             `json:"gas_limit,optional"`  // Gas 上限，0 表示自动估算（默认）
}

type GetTxByTxIdRequest struct {
	TxId      string `path:"txId"`
	ChainName string `form:"chain_name"`
}

type GetChainStatusRequest struct {
	ChainName string `path:"chainName"`
}

type EventSubscribeRequest struct {
	ChainName    string `json:"chain_name"`
	ContractName string `json:"contract_name,optional"`
	ContractAddr string `json:"contract_addr,optional"`
}

type EventPollRequest struct {
	SubscriptionId string `form:"subscription_id"`
	Count          int    `form:"count,optional"`
}

type EventUnsubscribeRequest struct {
	SubscriptionId string `path:"subscriptionId"`
}

type SubscribeByContractRequest struct {
	ContractConfigID uint `json:"contract_config_id"`
}

type UnsubscribeByContractRequest struct {
	ContractConfigID string `path:"contractConfigId"`
}

type CreateTenantRequest struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Phone    string `json:"phone,optional"`
	Plan     string `json:"plan,optional"`
	Password string `json:"password"`
}

type TenantIdPathRequest struct {
	Id uint `path:"id"`
}

type ListTenantsRequest struct {
	Page     int `form:"page,optional"`
	PageSize int `form:"page_size,optional"`
}

type CreateAPIKeyRequest struct {
	Name        string `json:"name,optional"`
	Permissions string `json:"permissions,optional"`
	IpWhitelist string `json:"ip_whitelist,optional"`
	ExpiresIn   int    `json:"expires_in,optional"`
}

type ListAPIKeysRequest struct {
	Page     int `form:"page,optional"`
	PageSize int `form:"page_size,optional"`
}

type NodeConfig struct {
	NodeAddr    string `json:"node_addr"`
	ConnCnt     int    `json:"conn_cnt,optional"`
	EnableTls   bool   `json:"enable_tls,optional"`
	TlsHostName string `json:"tls_host_name,optional"`
	CaCert      string `json:"ca_cert,optional"`
}

type CreateChainConfigRequest struct {
	ChainName       string       `json:"chain_name"`
	ChainType       string       `json:"chain_type"`
	Enable          bool         `json:"enable,optional"`
	ChainId         string       `json:"chain_id,optional"`
	AuthType        string       `json:"auth_type,optional"`
	OrgId           string       `json:"org_id,optional"`
	HashType        string       `json:"hash_type,optional"`
	SignKey         string       `json:"sign_key,optional"`
	SignCert        string       `json:"sign_cert,optional"`
	UserTlsKey      string       `json:"user_tls_key,optional"`
	UserTlsCert     string       `json:"user_tls_cert,optional"`
	UserEncKey      string       `json:"user_enc_key,optional"`
	UserEncCert     string       `json:"user_enc_cert,optional"`
	ProxyUrl        string       `json:"proxy_url,optional"`
	EthChainId      int64        `json:"eth_chain_id,optional"`
	HttpUrl         string       `json:"http_url,optional"`
	WebsocketUrl    string       `json:"websocket_url,optional"`
	PrivateKey      string       `json:"private_key,optional"`
	SolRpcUrl       string       `json:"sol_rpc_url,optional"`
	SolPrivateKey   string       `json:"sol_private_key,optional"`
	CommitmentLevel string       `json:"commitment_level,optional"`
	SkipPreflight   bool         `json:"skip_preflight,optional"`
	MaxRetries      int          `json:"max_retries,optional"`
	Nodes           []NodeConfig `json:"nodes,optional"`
}

type ChainConfigIdPathRequest struct {
	Id uint `path:"id"`
}

type UpdateChainConfigRequest struct {
	Id uint `path:"id"`
	CreateChainConfigRequest
}

type CreateContractConfigRequest struct {
	ChainConfigId   uint   `path:"chainConfigId"`
	ContractName    string `json:"contract_name"`
	ContractAddr    string `json:"contract_addr,optional"`
	AbiJson         string `json:"abi_json,optional"`
	EnableSubscribe bool   `json:"enable_subscribe,optional"`
	ExtraConf       string `json:"extra_conf,optional"`
}

type ListContractConfigsRequest struct {
	ChainConfigId uint `path:"chainConfigId"`
}

type GetContractConfigRequest struct {
	ChainConfigId uint `path:"chainConfigId"`
	Id            uint `path:"id"`
}

type UpdateContractConfigRequest struct {
	ChainConfigId   uint   `path:"chainConfigId"`
	Id              uint   `path:"id"`
	ContractName    string `json:"contract_name"`
	ContractAddr    string `json:"contract_addr,optional"`
	AbiJson         string `json:"abi_json,optional"`
	EnableSubscribe bool   `json:"enable_subscribe,optional"`
	ExtraConf       string `json:"extra_conf,optional"`
}

type DeleteContractConfigRequest struct {
	ChainConfigId uint `path:"chainConfigId"`
	Id            uint `path:"id"`
}

type ListUsersRequest struct {
	Page     int `form:"page,optional"`
	PageSize int `form:"page_size,optional"`
}

type ListCallLogsRequest struct {
	Page         int    `form:"page,optional"`
	PageSize     int    `form:"page_size,optional"`
	ChainName    string `form:"chain_name,optional"`
	ContractName string `form:"contract_name,optional"`
	MethodType   int    `form:"method_type,optional"` // 调用类型筛选：1-写链(Invoke) 2-读链(Query)
	Status       string `form:"status,optional"`
	StartTime    string `form:"start_time,optional"`
	EndTime      string `form:"end_time,optional"`
}

type ListBillsRequest struct {
	Page     int    `form:"page,optional"`
	PageSize int    `form:"page_size,optional"`
	BillType string `form:"bill_type,optional"` // 账单类型筛选：daily 或 monthly
}

type GenerateBillsRequest struct {
	Type string `json:"type"` // daily 或 monthly
}

type ListAuditLogsRequest struct {
	Page      int    `form:"page,optional"`
	PageSize  int    `form:"page_size,optional"`
	Action    string `form:"action,optional"`
	UserId    uint   `form:"user_id,optional"`
	StartTime string `form:"start_time,optional"`
	EndTime   string `form:"end_time,optional"`
}
