// Code generated by goctl. DO NOT EDIT.
// Source: chaininteractive.proto

package server

import (
	"context"

	"github.com/jackz-jones/blockchain-interactive-service/internal/logic"
	"github.com/jackz-jones/blockchain-interactive-service/internal/svc"
	"github.com/jackz-jones/blockchain-interactive-service/pb"
)

type ChainInteractiveServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedChainInteractiveServer
}

func NewChainInteractiveServer(svcCtx *svc.ServiceContext) *ChainInteractiveServer {
	return &ChainInteractiveServer{
		svcCtx: svcCtx,
	}
}

// GetTxByTxId 查询交易详情
func (s *ChainInteractiveServer) GetTxByTxId(ctx context.Context, in *__.GetTxByTxIdRequest) (*__.TxResponse, error) {
	l := logic.NewGetTxByTxIdLogic(ctx, s.svcCtx)
	return l.GetTxByTxId(in)
}

// CallContract 请求本地链合约，给提单平台用的
func (s *ChainInteractiveServer) CallContract(ctx context.Context, in *__.CallContractRequest) (*__.TxResponse, error) {
	l := logic.NewCallContractLogic(ctx, s.svcCtx)
	return l.CallContract(in)
}

// GetAvailableChainAndContractNames 获取本地可访问的所有链名称，以及旗下的合约名称
func (s *ChainInteractiveServer) GetAvailableChainAndContractNames(ctx context.Context, in *__.GetAvailableChainAndContractNamesRequest) (*__.GetAvailableChainAndContractNamesResponse, error) {
	l := logic.NewGetAvailableChainAndContractNamesLogic(ctx, s.svcCtx)
	return l.GetAvailableChainAndContractNames(in)
}
