// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	apikey "github.com/jackz-jones/blockchain-interactive-service/internal/handler/apikey"
	"github.com/jackz-jones/blockchain-interactive-service/internal/handler/auth"
	chain "github.com/jackz-jones/blockchain-interactive-service/internal/handler/chain"
	chainconfig "github.com/jackz-jones/blockchain-interactive-service/internal/handler/chainconfig"
	contractconfig "github.com/jackz-jones/blockchain-interactive-service/internal/handler/contractconfig"
	dashboard "github.com/jackz-jones/blockchain-interactive-service/internal/handler/dashboard"
	event "github.com/jackz-jones/blockchain-interactive-service/internal/handler/event"
	tenant "github.com/jackz-jones/blockchain-interactive-service/internal/handler/tenant"
	user "github.com/jackz-jones/blockchain-interactive-service/internal/handler/user"
	"github.com/jackz-jones/blockchain-interactive-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	// 公开路由（无需认证）
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/register",
				Handler: auth.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/validate",
				Handler: auth.ValidateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	// ========== 区块链核心操作路由 ==========
	// 仅区块链核心操作挂载 QuotaMiddleware，配额统计仅针对链上资源消耗
	// 业内 BaaS 标准：只有调用合约、部署合约、发送交易等链上操作才计配额
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.AuditMiddleware, serverCtx.RateLimitMiddleware, serverCtx.QuotaMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/contract/call",
					Handler: chain.CallContractHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	// ========== 区块链事件订阅路由 ==========
	// 订阅合约事件涉及链上资源，计配额
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.AuditMiddleware, serverCtx.RateLimitMiddleware, serverCtx.QuotaMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/events/subscribe-by-contract",
					Handler: event.SubscribeByContractHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	// ========== Web 平台管理路由（不计配额） ==========
	// 查询链状态、查看交易、管理配置、Dashboard 统计等均为平台操作，不消耗链上资源
	// 仅挂载认证、审计、限流中间件，不挂载 QuotaMiddleware
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.AuditMiddleware, serverCtx.RateLimitMiddleware},
			[]rest.Route{
				// 链查询（只读，不计配额）
				{
					Method:  http.MethodGet,
					Path:    "/tx/:txId",
					Handler: chain.GetTxByTxIdHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/chains",
					Handler: chain.GetAvailableChainsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/chains/:chainName/status",
					Handler: chain.GetChainStatusHandler(serverCtx),
				},
				// 事件查询（只读，不计配额）
				{
					Method:  http.MethodGet,
					Path:    "/events/subscriptions",
					Handler: event.ListSubscriptionsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/events/available-contracts",
					Handler: event.ListAvailableContractsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/events/recent/:contractConfigId",
					Handler: event.RecentEventsHandler(serverCtx),
				},
				// 取消订阅（Web 平台操作，不请求链节点，不计配额）
				{
					Method:  http.MethodDelete,
					Path:    "/events/subscribe-by-contract/:contractConfigId",
					Handler: event.UnsubscribeByContractHandler(serverCtx),
				},
				// 更新订阅配置（Web 平台操作，不计配额）
				{
					Method:  http.MethodPut,
					Path:    "/events/subscribe-by-contract/:contractConfigId",
					Handler: event.UpdateSubscriptionHandler(serverCtx),
				},
				// 链配置管理（平台操作，不计配额）
				{
					Method:  http.MethodPost,
					Path:    "/chain-configs",
					Handler: chainconfig.CreateChainConfigHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/chain-configs",
					Handler: chainconfig.ListChainConfigsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/chain-configs/:id",
					Handler: chainconfig.GetChainConfigDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/chain-configs/:id",
					Handler: chainconfig.UpdateChainConfigHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/chain-configs/:id",
					Handler: chainconfig.DeleteChainConfigHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/chain-configs/:id/test-connection",
					Handler: chainconfig.TestChainConnectionHandler(serverCtx),
				},
				// 合约配置管理（平台操作，不计配额）
				{
					Method:  http.MethodPost,
					Path:    "/chain-configs/:chainConfigId/contracts",
					Handler: contractconfig.CreateContractConfigHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/chain-configs/:chainConfigId/contracts",
					Handler: contractconfig.ListContractConfigsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/chain-configs/:chainConfigId/contracts/:id",
					Handler: contractconfig.GetContractConfigHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/chain-configs/:chainConfigId/contracts/:id",
					Handler: contractconfig.UpdateContractConfigHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/chain-configs/:chainConfigId/contracts/:id",
					Handler: contractconfig.DeleteContractConfigHandler(serverCtx),
				},
				// 租户管理（平台操作，不计配额）
				{
					Method:  http.MethodPost,
					Path:    "/tenants",
					Handler: tenant.CreateTenantHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/tenants/:id",
					Handler: tenant.GetTenantHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/tenants",
					Handler: tenant.ListTenantsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/tenants/:id/disable",
					Handler: tenant.DisableTenantHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/tenants/:id/enable",
					Handler: tenant.EnableTenantHandler(serverCtx),
				},
				// API Key 管理（平台操作，不计配额）
				{
					Method:  http.MethodPost,
					Path:    "/api-keys",
					Handler: apikey.CreateAPIKeyHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api-keys",
					Handler: apikey.ListAPIKeysHandler(serverCtx),
				},
				// 用户管理（平台操作，不计配额）
				{
					Method:  http.MethodGet,
					Path:    "/users",
					Handler: user.ListUsersHandler(serverCtx),
				},
				// Dashboard 统计（平台查询，不计配额）
				{
					Method:  http.MethodGet,
					Path:    "/dashboard/overview",
					Handler: dashboard.OverviewHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/dashboard/call-logs",
					Handler: dashboard.ListCallLogsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/dashboard/usage-stats",
					Handler: dashboard.GetUsageStatsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/dashboard/usage-stats-trend",
					Handler: dashboard.GetUsageStatsTrendHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/dashboard/bills",
					Handler: dashboard.ListBillsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/dashboard/realtime-cost",
					Handler: dashboard.GetRealtimeCostHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/dashboard/bills/generate",
					Handler: dashboard.GenerateBillsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/dashboard/audit-logs",
					Handler: dashboard.ListAuditLogsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)
}
