// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	apikey "github.com/jackz-jones/blockchain-interactive-service/internal/handler/apikey"
	"github.com/jackz-jones/blockchain-interactive-service/internal/handler/auth"
	chain "github.com/jackz-jones/blockchain-interactive-service/internal/handler/chain"
	chainconfig "github.com/jackz-jones/blockchain-interactive-service/internal/handler/chainconfig"
	contractconfig "github.com/jackz-jones/blockchain-interactive-service/internal/handler/contractconfig"
	dashboard "github.com/jackz-jones/blockchain-interactive-service/internal/handler/dashboard"
	event "github.com/jackz-jones/blockchain-interactive-service/internal/handler/event"
	tenant "github.com/jackz-jones/blockchain-interactive-service/internal/handler/tenant"
	user "github.com/jackz-jones/blockchain-interactive-service/internal/handler/user"
	"github.com/jackz-jones/blockchain-interactive-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	// 公开路由（无需认证）
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/register",
				Handler: auth.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/validate",
				Handler: auth.ValidateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.RateLimitMiddleware, serverCtx.QuotaMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/contract/call",
					Handler: chain.CallContractHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/tx/:txId",
					Handler: chain.GetTxByTxIdHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/chains",
					Handler: chain.GetAvailableChainsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/chains/:chainName/status",
					Handler: chain.GetChainStatusHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.RateLimitMiddleware, serverCtx.QuotaMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/events/subscribe",
					Handler: event.SubscribeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/events/poll",
					Handler: event.PollHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/events/subscribe/:subscriptionId",
					Handler: event.UnsubscribeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.RateLimitMiddleware, serverCtx.QuotaMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/tenants",
					Handler: tenant.CreateTenantHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/tenants/:id",
					Handler: tenant.GetTenantHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/tenants",
					Handler: tenant.ListTenantsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/tenants/:id/disable",
					Handler: tenant.DisableTenantHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/tenants/:id/enable",
					Handler: tenant.EnableTenantHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.RateLimitMiddleware, serverCtx.QuotaMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api-keys",
					Handler: apikey.CreateAPIKeyHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api-keys",
					Handler: apikey.ListAPIKeysHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.RateLimitMiddleware, serverCtx.QuotaMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/chain-configs",
					Handler: chainconfig.CreateChainConfigHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/chain-configs",
					Handler: chainconfig.ListChainConfigsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/chain-configs/:id",
					Handler: chainconfig.GetChainConfigDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/chain-configs/:id",
					Handler: chainconfig.UpdateChainConfigHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/chain-configs/:id",
					Handler: chainconfig.DeleteChainConfigHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/chain-configs/:id/test-connection",
					Handler: chainconfig.TestChainConnectionHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.RateLimitMiddleware, serverCtx.QuotaMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/chain-configs/:chainConfigId/contracts",
					Handler: contractconfig.CreateContractConfigHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/chain-configs/:chainConfigId/contracts",
					Handler: contractconfig.ListContractConfigsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/chain-configs/:chainConfigId/contracts/:id",
					Handler: contractconfig.GetContractConfigHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/chain-configs/:chainConfigId/contracts/:id",
					Handler: contractconfig.UpdateContractConfigHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/chain-configs/:chainConfigId/contracts/:id",
					Handler: contractconfig.DeleteContractConfigHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.RateLimitMiddleware, serverCtx.QuotaMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/users",
					Handler: user.ListUsersHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.RateLimitMiddleware, serverCtx.QuotaMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/dashboard/overview",
					Handler: dashboard.OverviewHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/dashboard/call-logs",
					Handler: dashboard.ListCallLogsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/dashboard/usage-stats",
					Handler: dashboard.GetUsageStatsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/dashboard/bills",
					Handler: dashboard.ListBillsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/dashboard/audit-logs",
					Handler: dashboard.ListAuditLogsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)
}
