// Code generated by goctl. DO NOT EDIT.
// Source: chaininteractive.proto

package chaininteractive

import (
	"context"

	"github.com/jackz-jones/blockchain-interactive-service/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CallContractRequest                       = __.CallContractRequest
	ChainAndContractName                      = __.ChainAndContractName
	ContractDesc                              = __.ContractDesc
	ContractEventResponse                     = __.ContractEventResponse
	GetAvailableChainAndContractNamesRequest  = __.GetAvailableChainAndContractNamesRequest
	GetAvailableChainAndContractNamesResponse = __.GetAvailableChainAndContractNamesResponse
	GetTxByTxIdRequest                        = __.GetTxByTxIdRequest
	KeyValuePair                              = __.KeyValuePair
	SubscribeContractEventsRequest            = __.SubscribeContractEventsRequest
	TxData                                    = __.TxData
	TxResponse                                = __.TxResponse

	ChainInteractive interface {
		// GetTxByTxId 查询交易详情
		GetTxByTxId(ctx context.Context, in *GetTxByTxIdRequest, opts ...grpc.CallOption) (*TxResponse, error)
		// CallContract 调用指定链上的智能合约
		CallContract(ctx context.Context, in *CallContractRequest, opts ...grpc.CallOption) (*TxResponse, error)
		// GetAvailableChainAndContractNames 获取本地可访问的所有链名称，以及旗下的合约名称
		GetAvailableChainAndContractNames(ctx context.Context, in *GetAvailableChainAndContractNamesRequest, opts ...grpc.CallOption) (*GetAvailableChainAndContractNamesResponse, error)
		// SubscribeContractEvents 订阅合约事件（服务端流式推送）
		SubscribeContractEvents(ctx context.Context, in *SubscribeContractEventsRequest, opts ...grpc.CallOption) (__.ChainInteractive_SubscribeContractEventsClient, error)
	}

	defaultChainInteractive struct {
		cli zrpc.Client
	}
)

func NewChainInteractive(cli zrpc.Client) ChainInteractive {
	return &defaultChainInteractive{
		cli: cli,
	}
}

// GetTxByTxId 查询交易详情
func (m *defaultChainInteractive) GetTxByTxId(ctx context.Context, in *GetTxByTxIdRequest, opts ...grpc.CallOption) (*TxResponse, error) {
	client := __.NewChainInteractiveClient(m.cli.Conn())
	return client.GetTxByTxId(ctx, in, opts...)
}

// CallContract 调用指定链上的智能合约
func (m *defaultChainInteractive) CallContract(ctx context.Context, in *CallContractRequest, opts ...grpc.CallOption) (*TxResponse, error) {
	client := __.NewChainInteractiveClient(m.cli.Conn())
	return client.CallContract(ctx, in, opts...)
}

// GetAvailableChainAndContractNames 获取本地可访问的所有链名称，以及旗下的合约名称
func (m *defaultChainInteractive) GetAvailableChainAndContractNames(ctx context.Context, in *GetAvailableChainAndContractNamesRequest, opts ...grpc.CallOption) (*GetAvailableChainAndContractNamesResponse, error) {
	client := __.NewChainInteractiveClient(m.cli.Conn())
	return client.GetAvailableChainAndContractNames(ctx, in, opts...)
}

// SubscribeContractEvents 订阅合约事件（服务端流式推送）
func (m *defaultChainInteractive) SubscribeContractEvents(ctx context.Context, in *SubscribeContractEventsRequest, opts ...grpc.CallOption) (__.ChainInteractive_SubscribeContractEventsClient, error) {
	client := __.NewChainInteractiveClient(m.cli.Conn())
	return client.SubscribeContractEvents(ctx, in, opts...)
}
