// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.20.3
// source: proto/chaininteractive.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 合约调用类型
type MethodType int32

const (
	MethodType_UNDEFINED MethodType = 0 // 未知类型
	MethodType_Invoke    MethodType = 1 // 写链类型
	MethodType_Query     MethodType = 2 // 读链类型
)

// Enum value maps for MethodType.
var (
	MethodType_name = map[int32]string{
		0: "UNDEFINED",
		1: "Invoke",
		2: "Query",
	}
	MethodType_value = map[string]int32{
		"UNDEFINED": 0,
		"Invoke":    1,
		"Query":     2,
	}
)

func (x MethodType) Enum() *MethodType {
	p := new(MethodType)
	*p = x
	return p
}

func (x MethodType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MethodType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_chaininteractive_proto_enumTypes[0].Descriptor()
}

func (MethodType) Type() protoreflect.EnumType {
	return &file_proto_chaininteractive_proto_enumTypes[0]
}

func (x MethodType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MethodType.Descriptor instead.
func (MethodType) EnumDescriptor() ([]byte, []int) {
	return file_proto_chaininteractive_proto_rawDescGZIP(), []int{0}
}

// 链类型
type ChainType int32

const (
	ChainType_Ethereum   ChainType = 0 // 以太坊
	ChainType_Chainmaker ChainType = 1 // 长安链
	ChainType_Solana     ChainType = 2 // Solana链
)

// Enum value maps for ChainType.
var (
	ChainType_name = map[int32]string{
		0: "Ethereum",
		1: "Chainmaker",
		2: "Solana",
	}
	ChainType_value = map[string]int32{
		"Ethereum":   0,
		"Chainmaker": 1,
		"Solana":     2,
	}
)

func (x ChainType) Enum() *ChainType {
	p := new(ChainType)
	*p = x
	return p
}

func (x ChainType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChainType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_chaininteractive_proto_enumTypes[1].Descriptor()
}

func (ChainType) Type() protoreflect.EnumType {
	return &file_proto_chaininteractive_proto_enumTypes[1]
}

func (x ChainType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChainType.Descriptor instead.
func (ChainType) EnumDescriptor() ([]byte, []int) {
	return file_proto_chaininteractive_proto_rawDescGZIP(), []int{1}
}

type GetTxByTxIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"` // 请求id，日志追踪
	TxId      string `protobuf:"bytes,2,opt,name=txId,proto3" json:"txId,omitempty"`           // 交易 id
	ChainName string `protobuf:"bytes,3,opt,name=chainName,proto3" json:"chainName,omitempty"` // 哪条链
}

func (x *GetTxByTxIdRequest) Reset() {
	*x = GetTxByTxIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chaininteractive_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTxByTxIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTxByTxIdRequest) ProtoMessage() {}

func (x *GetTxByTxIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaininteractive_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTxByTxIdRequest.ProtoReflect.Descriptor instead.
func (*GetTxByTxIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_chaininteractive_proto_rawDescGZIP(), []int{0}
}

func (x *GetTxByTxIdRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GetTxByTxIdRequest) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *GetTxByTxIdRequest) GetChainName() string {
	if x != nil {
		return x.ChainName
	}
	return ""
}

type TxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 错误码
	Msg  string  `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`    // 错误信息
	Data *TxData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`  // 交易结果
}

func (x *TxResponse) Reset() {
	*x = TxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chaininteractive_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxResponse) ProtoMessage() {}

func (x *TxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaininteractive_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxResponse.ProtoReflect.Descriptor instead.
func (*TxResponse) Descriptor() ([]byte, []int) {
	return file_proto_chaininteractive_proto_rawDescGZIP(), []int{1}
}

func (x *TxResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TxResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *TxResponse) GetData() *TxData {
	if x != nil {
		return x.Data
	}
	return nil
}

type TxData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChainName string `protobuf:"bytes,1,opt,name=chainName,proto3" json:"chainName,omitempty"` // 哪条链
	Content   string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`     // 交易内容，json 字符串
	Pending   bool   `protobuf:"varint,3,opt,name=pending,proto3" json:"pending,omitempty"`    // 是否打包块中，true 表示还没打包，false 表示已打包
	TxId      string `protobuf:"bytes,4,opt,name=txId,proto3" json:"txId,omitempty"`           // 交易 id
}

func (x *TxData) Reset() {
	*x = TxData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chaininteractive_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxData) ProtoMessage() {}

func (x *TxData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaininteractive_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxData.ProtoReflect.Descriptor instead.
func (*TxData) Descriptor() ([]byte, []int) {
	return file_proto_chaininteractive_proto_rawDescGZIP(), []int{2}
}

func (x *TxData) GetChainName() string {
	if x != nil {
		return x.ChainName
	}
	return ""
}

func (x *TxData) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TxData) GetPending() bool {
	if x != nil {
		return x.Pending
	}
	return false
}

func (x *TxData) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

// 合约调用参数 key-value
type KeyValuePair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`     // 参数名称
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // 参数值
}

func (x *KeyValuePair) Reset() {
	*x = KeyValuePair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chaininteractive_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyValuePair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValuePair) ProtoMessage() {}

func (x *KeyValuePair) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaininteractive_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValuePair.ProtoReflect.Descriptor instead.
func (*KeyValuePair) Descriptor() ([]byte, []int) {
	return file_proto_chaininteractive_proto_rawDescGZIP(), []int{3}
}

func (x *KeyValuePair) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValuePair) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type CallContractRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId      string          `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	ChainName      string          `protobuf:"bytes,2,opt,name=chainName,proto3" json:"chainName,omitempty"`                          // 哪条链
	ContractName   string          `protobuf:"bytes,3,opt,name=contractName,proto3" json:"contractName,omitempty"`                    // 合约名称
	ContractMethod string          `protobuf:"bytes,4,opt,name=contractMethod,proto3" json:"contractMethod,omitempty"`                // 合约方法
	KvPairs        []*KeyValuePair `protobuf:"bytes,5,rep,name=kvPairs,proto3" json:"kvPairs,omitempty"`                              // 合约参数
	MethodType     MethodType      `protobuf:"varint,6,opt,name=methodType,proto3,enum=proto.MethodType" json:"methodType,omitempty"` // 合约调用类型
	WithSyncResult bool            `protobuf:"varint,7,opt,name=withSyncResult,proto3" json:"withSyncResult,omitempty"`               // 异步还是同步上链
	TxTimeout      int64           `protobuf:"varint,8,opt,name=txTimeout,proto3" json:"txTimeout,omitempty"`                         // 交易超时时间，单位秒，默认会 30s
	GasLimit       int64           `protobuf:"varint,9,opt,name=gasLimit,proto3" json:"gasLimit,omitempty"`                           // Gas 上限，0 表示自动估算（默认）
}

func (x *CallContractRequest) Reset() {
	*x = CallContractRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chaininteractive_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallContractRequest) ProtoMessage() {}

func (x *CallContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaininteractive_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallContractRequest.ProtoReflect.Descriptor instead.
func (*CallContractRequest) Descriptor() ([]byte, []int) {
	return file_proto_chaininteractive_proto_rawDescGZIP(), []int{4}
}

func (x *CallContractRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CallContractRequest) GetChainName() string {
	if x != nil {
		return x.ChainName
	}
	return ""
}

func (x *CallContractRequest) GetContractName() string {
	if x != nil {
		return x.ContractName
	}
	return ""
}

func (x *CallContractRequest) GetContractMethod() string {
	if x != nil {
		return x.ContractMethod
	}
	return ""
}

func (x *CallContractRequest) GetKvPairs() []*KeyValuePair {
	if x != nil {
		return x.KvPairs
	}
	return nil
}

func (x *CallContractRequest) GetMethodType() MethodType {
	if x != nil {
		return x.MethodType
	}
	return MethodType_UNDEFINED
}

func (x *CallContractRequest) GetWithSyncResult() bool {
	if x != nil {
		return x.WithSyncResult
	}
	return false
}

func (x *CallContractRequest) GetTxTimeout() int64 {
	if x != nil {
		return x.TxTimeout
	}
	return 0
}

func (x *CallContractRequest) GetGasLimit() int64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

type GetAvailableChainAndContractNamesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
}

func (x *GetAvailableChainAndContractNamesRequest) Reset() {
	*x = GetAvailableChainAndContractNamesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chaininteractive_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAvailableChainAndContractNamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableChainAndContractNamesRequest) ProtoMessage() {}

func (x *GetAvailableChainAndContractNamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaininteractive_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableChainAndContractNamesRequest.ProtoReflect.Descriptor instead.
func (*GetAvailableChainAndContractNamesRequest) Descriptor() ([]byte, []int) {
	return file_proto_chaininteractive_proto_rawDescGZIP(), []int{5}
}

func (x *GetAvailableChainAndContractNamesRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ContractDesc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContractName    string `protobuf:"bytes,1,opt,name=contractName,proto3" json:"contractName,omitempty"`       // 合约配置名称
	ContractAddress string `protobuf:"bytes,2,opt,name=contractAddress,proto3" json:"contractAddress,omitempty"` // 合约地址，以太坊/Solana 合约会返回
	Abi             string `protobuf:"bytes,3,opt,name=abi,proto3" json:"abi,omitempty"`                         // 合约 ABI JSON，以太坊合约会返回
}

func (x *ContractDesc) Reset() {
	*x = ContractDesc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chaininteractive_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractDesc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractDesc) ProtoMessage() {}

func (x *ContractDesc) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaininteractive_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractDesc.ProtoReflect.Descriptor instead.
func (*ContractDesc) Descriptor() ([]byte, []int) {
	return file_proto_chaininteractive_proto_rawDescGZIP(), []int{6}
}

func (x *ContractDesc) GetContractName() string {
	if x != nil {
		return x.ContractName
	}
	return ""
}

func (x *ContractDesc) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *ContractDesc) GetAbi() string {
	if x != nil {
		return x.Abi
	}
	return ""
}

type ChainAndContractName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChainName     string          `protobuf:"bytes,1,opt,name=chainName,proto3" json:"chainName,omitempty"`                       // 链配置名称
	ChainType     ChainType       `protobuf:"varint,2,opt,name=chainType,proto3,enum=proto.ChainType" json:"chainType,omitempty"` // 链类型
	ContractDescs []*ContractDesc `protobuf:"bytes,3,rep,name=contractDescs,proto3" json:"contractDescs,omitempty"`               // 链下的合约配置列表
}

func (x *ChainAndContractName) Reset() {
	*x = ChainAndContractName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chaininteractive_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChainAndContractName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainAndContractName) ProtoMessage() {}

func (x *ChainAndContractName) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaininteractive_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainAndContractName.ProtoReflect.Descriptor instead.
func (*ChainAndContractName) Descriptor() ([]byte, []int) {
	return file_proto_chaininteractive_proto_rawDescGZIP(), []int{7}
}

func (x *ChainAndContractName) GetChainName() string {
	if x != nil {
		return x.ChainName
	}
	return ""
}

func (x *ChainAndContractName) GetChainType() ChainType {
	if x != nil {
		return x.ChainType
	}
	return ChainType_Ethereum
}

func (x *ChainAndContractName) GetContractDescs() []*ContractDesc {
	if x != nil {
		return x.ContractDescs
	}
	return nil
}

type GetAvailableChainAndContractNamesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32                   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string                  `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data []*ChainAndContractName `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetAvailableChainAndContractNamesResponse) Reset() {
	*x = GetAvailableChainAndContractNamesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chaininteractive_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAvailableChainAndContractNamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableChainAndContractNamesResponse) ProtoMessage() {}

func (x *GetAvailableChainAndContractNamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaininteractive_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableChainAndContractNamesResponse.ProtoReflect.Descriptor instead.
func (*GetAvailableChainAndContractNamesResponse) Descriptor() ([]byte, []int) {
	return file_proto_chaininteractive_proto_rawDescGZIP(), []int{8}
}

func (x *GetAvailableChainAndContractNamesResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetAvailableChainAndContractNamesResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetAvailableChainAndContractNamesResponse) GetData() []*ChainAndContractName {
	if x != nil {
		return x.Data
	}
	return nil
}

// SubscribeContractEvents 请求消息
type SubscribeContractEventsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId    string `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`       // 请求 ID，日志追踪
	ChainName    string `protobuf:"bytes,2,opt,name=chainName,proto3" json:"chainName,omitempty"`       // 链名称（必填）
	ContractName string `protobuf:"bytes,3,opt,name=contractName,proto3" json:"contractName,omitempty"` // 合约名称（可选，与 contractAddr 二选一）
	ContractAddr string `protobuf:"bytes,4,opt,name=contractAddr,proto3" json:"contractAddr,omitempty"` // 合约地址（可选，与 contractName 二选一）
}

func (x *SubscribeContractEventsRequest) Reset() {
	*x = SubscribeContractEventsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chaininteractive_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeContractEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeContractEventsRequest) ProtoMessage() {}

func (x *SubscribeContractEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaininteractive_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeContractEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeContractEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_chaininteractive_proto_rawDescGZIP(), []int{9}
}

func (x *SubscribeContractEventsRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SubscribeContractEventsRequest) GetChainName() string {
	if x != nil {
		return x.ChainName
	}
	return ""
}

func (x *SubscribeContractEventsRequest) GetContractName() string {
	if x != nil {
		return x.ContractName
	}
	return ""
}

func (x *SubscribeContractEventsRequest) GetContractAddr() string {
	if x != nil {
		return x.ContractAddr
	}
	return ""
}

// ContractEventResponse 事件流响应消息
type ContractEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventName       string `protobuf:"bytes,1,opt,name=eventName,proto3" json:"eventName,omitempty"`             // 事件名称
	ContractAddress string `protobuf:"bytes,2,opt,name=contractAddress,proto3" json:"contractAddress,omitempty"` // 合约地址
	TxHash          string `protobuf:"bytes,3,opt,name=txHash,proto3" json:"txHash,omitempty"`                   // 交易哈希
	BlockNumber     uint64 `protobuf:"varint,4,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`        // 区块号
	Data            string `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`                       // 事件数据 JSON 字符串
	Timestamp       int64  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`            // 事件时间戳（Unix 秒）
}

func (x *ContractEventResponse) Reset() {
	*x = ContractEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chaininteractive_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractEventResponse) ProtoMessage() {}

func (x *ContractEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chaininteractive_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractEventResponse.ProtoReflect.Descriptor instead.
func (*ContractEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_chaininteractive_proto_rawDescGZIP(), []int{10}
}

func (x *ContractEventResponse) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *ContractEventResponse) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *ContractEventResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *ContractEventResponse) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *ContractEventResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *ContractEventResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_chaininteractive_proto protoreflect.FileDescriptor

var file_proto_chaininteractive_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x64, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x54, 0x78, 0x42, 0x79,
	0x54, 0x78, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x78, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x78, 0x49, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x55, 0x0a, 0x0a, 0x54,
	0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12,
	0x21, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x78, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x6e, 0x0a, 0x06, 0x54, 0x78, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x78, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x78,
	0x49, 0x64, 0x22, 0x36, 0x0a, 0x0c, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x50, 0x61,
	0x69, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xe1, 0x02, 0x0a, 0x13, 0x43,
	0x61, 0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22,
	0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x4d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x2d, 0x0a, 0x07, 0x6b, 0x76,
	0x50, 0x61, 0x69, 0x72, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x50, 0x61, 0x69, 0x72,
	0x52, 0x07, 0x6b, 0x76, 0x50, 0x61, 0x69, 0x72, 0x73, 0x12, 0x31, 0x0a, 0x0a, 0x6d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x0a, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x0e,
	0x77, 0x69, 0x74, 0x68, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x77, 0x69, 0x74, 0x68, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x78, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75,
	0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x78, 0x54, 0x69, 0x6d, 0x65, 0x6f,
	0x75, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x73, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x67, 0x61, 0x73, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x48,
	0x0a, 0x28, 0x47, 0x65, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x68,
	0x61, 0x69, 0x6e, 0x41, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x22, 0x6e, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x44, 0x65, 0x73, 0x63, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x0f,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x62, 0x69, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x62, 0x69, 0x22, 0x9f, 0x01, 0x0a, 0x14, 0x43, 0x68, 0x61,
	0x69, 0x6e, 0x41, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x2e, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x61, 0x69, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x39, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x44, 0x65, 0x73, 0x63, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x44, 0x65, 0x73, 0x63, 0x52, 0x0d, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x44, 0x65, 0x73, 0x63, 0x73, 0x22, 0x82, 0x01, 0x0a, 0x29, 0x47,
	0x65, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e,
	0x41, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x2f,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x41, 0x6e, 0x64, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0xa4, 0x01, 0x0a, 0x1e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22,
	0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x41, 0x64,
	0x64, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x41, 0x64, 0x64, 0x72, 0x22, 0xcb, 0x01, 0x0a, 0x15, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28,
	0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x78, 0x48, 0x61,
	0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x78, 0x48, 0x61, 0x73, 0x68,
	0x12, 0x20, 0x0a, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2a, 0x32, 0x0a, 0x0a, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x0a, 0x0a, 0x06, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x10, 0x01, 0x12, 0x09, 0x0a,
	0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x10, 0x02, 0x2a, 0x35, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x69,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x45, 0x74, 0x68, 0x65, 0x72, 0x65, 0x75,
	0x6d, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x6d, 0x61, 0x6b, 0x65,
	0x72, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x6f, 0x6c, 0x61, 0x6e, 0x61, 0x10, 0x02, 0x32,
	0x81, 0x03, 0x0a, 0x10, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x12, 0x3d, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x54, 0x78, 0x42, 0x79, 0x54,
	0x78, 0x49, 0x64, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x54,
	0x78, 0x42, 0x79, 0x54, 0x78, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0c, 0x43, 0x61, 0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x61, 0x6c, 0x6c,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x88, 0x01, 0x0a, 0x21, 0x47, 0x65, 0x74, 0x41, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x41, 0x6e, 0x64, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x2f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x43,
	0x68, 0x61, 0x69, 0x6e, 0x41, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x30, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x43, 0x68, 0x61, 0x69, 0x6e, 0x41, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x62, 0x0a, 0x17, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x25, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x30, 0x01, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_chaininteractive_proto_rawDescOnce sync.Once
	file_proto_chaininteractive_proto_rawDescData = file_proto_chaininteractive_proto_rawDesc
)

func file_proto_chaininteractive_proto_rawDescGZIP() []byte {
	file_proto_chaininteractive_proto_rawDescOnce.Do(func() {
		file_proto_chaininteractive_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_chaininteractive_proto_rawDescData)
	})
	return file_proto_chaininteractive_proto_rawDescData
}

var file_proto_chaininteractive_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_chaininteractive_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_chaininteractive_proto_goTypes = []interface{}{
	(MethodType)(0),             // 0: proto.MethodType
	(ChainType)(0),              // 1: proto.ChainType
	(*GetTxByTxIdRequest)(nil),  // 2: proto.GetTxByTxIdRequest
	(*TxResponse)(nil),          // 3: proto.TxResponse
	(*TxData)(nil),              // 4: proto.TxData
	(*KeyValuePair)(nil),        // 5: proto.KeyValuePair
	(*CallContractRequest)(nil), // 6: proto.CallContractRequest
	(*GetAvailableChainAndContractNamesRequest)(nil),  // 7: proto.GetAvailableChainAndContractNamesRequest
	(*ContractDesc)(nil),                              // 8: proto.ContractDesc
	(*ChainAndContractName)(nil),                      // 9: proto.ChainAndContractName
	(*GetAvailableChainAndContractNamesResponse)(nil), // 10: proto.GetAvailableChainAndContractNamesResponse
	(*SubscribeContractEventsRequest)(nil),            // 11: proto.SubscribeContractEventsRequest
	(*ContractEventResponse)(nil),                     // 12: proto.ContractEventResponse
}
var file_proto_chaininteractive_proto_depIdxs = []int32{
	4,  // 0: proto.TxResponse.data:type_name -> proto.TxData
	5,  // 1: proto.CallContractRequest.kvPairs:type_name -> proto.KeyValuePair
	0,  // 2: proto.CallContractRequest.methodType:type_name -> proto.MethodType
	1,  // 3: proto.ChainAndContractName.chainType:type_name -> proto.ChainType
	8,  // 4: proto.ChainAndContractName.contractDescs:type_name -> proto.ContractDesc
	9,  // 5: proto.GetAvailableChainAndContractNamesResponse.data:type_name -> proto.ChainAndContractName
	2,  // 6: proto.ChainInteractive.GetTxByTxId:input_type -> proto.GetTxByTxIdRequest
	6,  // 7: proto.ChainInteractive.CallContract:input_type -> proto.CallContractRequest
	7,  // 8: proto.ChainInteractive.GetAvailableChainAndContractNames:input_type -> proto.GetAvailableChainAndContractNamesRequest
	11, // 9: proto.ChainInteractive.SubscribeContractEvents:input_type -> proto.SubscribeContractEventsRequest
	3,  // 10: proto.ChainInteractive.GetTxByTxId:output_type -> proto.TxResponse
	3,  // 11: proto.ChainInteractive.CallContract:output_type -> proto.TxResponse
	10, // 12: proto.ChainInteractive.GetAvailableChainAndContractNames:output_type -> proto.GetAvailableChainAndContractNamesResponse
	12, // 13: proto.ChainInteractive.SubscribeContractEvents:output_type -> proto.ContractEventResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_chaininteractive_proto_init() }
func file_proto_chaininteractive_proto_init() {
	if File_proto_chaininteractive_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_chaininteractive_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTxByTxIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chaininteractive_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chaininteractive_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chaininteractive_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyValuePair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chaininteractive_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallContractRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chaininteractive_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAvailableChainAndContractNamesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chaininteractive_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractDesc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chaininteractive_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChainAndContractName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chaininteractive_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAvailableChainAndContractNamesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chaininteractive_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeContractEventsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chaininteractive_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_chaininteractive_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_chaininteractive_proto_goTypes,
		DependencyIndexes: file_proto_chaininteractive_proto_depIdxs,
		EnumInfos:         file_proto_chaininteractive_proto_enumTypes,
		MessageInfos:      file_proto_chaininteractive_proto_msgTypes,
	}.Build()
	File_proto_chaininteractive_proto = out.File
	file_proto_chaininteractive_proto_rawDesc = nil
	file_proto_chaininteractive_proto_goTypes = nil
	file_proto_chaininteractive_proto_depIdxs = nil
}
