// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.20.3
// source: proto/chaininteractive.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ChainInteractive_GetTxByTxId_FullMethodName                       = "/proto.ChainInteractive/GetTxByTxId"
	ChainInteractive_CallContract_FullMethodName                      = "/proto.ChainInteractive/CallContract"
	ChainInteractive_GetAvailableChainAndContractNames_FullMethodName = "/proto.ChainInteractive/GetAvailableChainAndContractNames"
)

// ChainInteractiveClient is the client API for ChainInteractive service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChainInteractiveClient interface {
	// GetTxByTxId 查询交易详情
	GetTxByTxId(ctx context.Context, in *GetTxByTxIdRequest, opts ...grpc.CallOption) (*TxResponse, error)
	// CallContract 请求本地链合约，给提单平台用的
	CallContract(ctx context.Context, in *CallContractRequest, opts ...grpc.CallOption) (*TxResponse, error)
	// GetAvailableChainAndContractNames 获取本地可访问的所有链名称，以及旗下的合约名称
	GetAvailableChainAndContractNames(ctx context.Context, in *GetAvailableChainAndContractNamesRequest, opts ...grpc.CallOption) (*GetAvailableChainAndContractNamesResponse, error)
}

type chainInteractiveClient struct {
	cc grpc.ClientConnInterface
}

func NewChainInteractiveClient(cc grpc.ClientConnInterface) ChainInteractiveClient {
	return &chainInteractiveClient{cc}
}

func (c *chainInteractiveClient) GetTxByTxId(ctx context.Context, in *GetTxByTxIdRequest, opts ...grpc.CallOption) (*TxResponse, error) {
	out := new(TxResponse)
	err := c.cc.Invoke(ctx, ChainInteractive_GetTxByTxId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainInteractiveClient) CallContract(ctx context.Context, in *CallContractRequest, opts ...grpc.CallOption) (*TxResponse, error) {
	out := new(TxResponse)
	err := c.cc.Invoke(ctx, ChainInteractive_CallContract_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainInteractiveClient) GetAvailableChainAndContractNames(ctx context.Context, in *GetAvailableChainAndContractNamesRequest, opts ...grpc.CallOption) (*GetAvailableChainAndContractNamesResponse, error) {
	out := new(GetAvailableChainAndContractNamesResponse)
	err := c.cc.Invoke(ctx, ChainInteractive_GetAvailableChainAndContractNames_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChainInteractiveServer is the server API for ChainInteractive service.
// All implementations must embed UnimplementedChainInteractiveServer
// for forward compatibility
type ChainInteractiveServer interface {
	// GetTxByTxId 查询交易详情
	GetTxByTxId(context.Context, *GetTxByTxIdRequest) (*TxResponse, error)
	// CallContract 请求本地链合约，给提单平台用的
	CallContract(context.Context, *CallContractRequest) (*TxResponse, error)
	// GetAvailableChainAndContractNames 获取本地可访问的所有链名称，以及旗下的合约名称
	GetAvailableChainAndContractNames(context.Context, *GetAvailableChainAndContractNamesRequest) (*GetAvailableChainAndContractNamesResponse, error)
	mustEmbedUnimplementedChainInteractiveServer()
}

// UnimplementedChainInteractiveServer must be embedded to have forward compatible implementations.
type UnimplementedChainInteractiveServer struct {
}

func (UnimplementedChainInteractiveServer) GetTxByTxId(context.Context, *GetTxByTxIdRequest) (*TxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTxByTxId not implemented")
}
func (UnimplementedChainInteractiveServer) CallContract(context.Context, *CallContractRequest) (*TxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallContract not implemented")
}
func (UnimplementedChainInteractiveServer) GetAvailableChainAndContractNames(context.Context, *GetAvailableChainAndContractNamesRequest) (*GetAvailableChainAndContractNamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAvailableChainAndContractNames not implemented")
}
func (UnimplementedChainInteractiveServer) mustEmbedUnimplementedChainInteractiveServer() {}

// UnsafeChainInteractiveServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChainInteractiveServer will
// result in compilation errors.
type UnsafeChainInteractiveServer interface {
	mustEmbedUnimplementedChainInteractiveServer()
}

func RegisterChainInteractiveServer(s grpc.ServiceRegistrar, srv ChainInteractiveServer) {
	s.RegisterService(&ChainInteractive_ServiceDesc, srv)
}

func _ChainInteractive_GetTxByTxId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTxByTxIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainInteractiveServer).GetTxByTxId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainInteractive_GetTxByTxId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainInteractiveServer).GetTxByTxId(ctx, req.(*GetTxByTxIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainInteractive_CallContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallContractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainInteractiveServer).CallContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainInteractive_CallContract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainInteractiveServer).CallContract(ctx, req.(*CallContractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainInteractive_GetAvailableChainAndContractNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvailableChainAndContractNamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainInteractiveServer).GetAvailableChainAndContractNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainInteractive_GetAvailableChainAndContractNames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainInteractiveServer).GetAvailableChainAndContractNames(ctx, req.(*GetAvailableChainAndContractNamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChainInteractive_ServiceDesc is the grpc.ServiceDesc for ChainInteractive service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChainInteractive_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ChainInteractive",
	HandlerType: (*ChainInteractiveServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTxByTxId",
			Handler:    _ChainInteractive_GetTxByTxId_Handler,
		},
		{
			MethodName: "CallContract",
			Handler:    _ChainInteractive_CallContract_Handler,
		},
		{
			MethodName: "GetAvailableChainAndContractNames",
			Handler:    _ChainInteractive_GetAvailableChainAndContractNames_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/chaininteractive.proto",
}
